name: my_env
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  # Core ML packages
  - cudatoolkit=11.8
  - tensorboard=2.18.0
  - scikit-learn=1.5.2
  - scipy=1.13.1
  - numpy=1.26.3

  # Jupyter related
  - jupyter=1.1.1
  - jupyterlab=4.0.0
  - ipykernel
  - ipython
  - ipywidgets

  # Visualization and media
  - matplotlib=3.9.2
  - pillow=10.2.0
  - opencv=4.10.0

  # Utils and helpers
  - tqdm=4.66.5
  - pyyaml
  - requests
  - joblib=1.4.2

  # Additional dependencies
  - pip
  - pip:
    - clearml==1.16.4
    - einops==0.8.0
    - fairseq @ git+https://github.com/Tps-F/fairseq.git@ff08af27e302625a27d3502b0791a9367c8af0c7
    - hydra-core==1.3.2
    - mediapy==1.2.2
    - soundfile==0.12.1
    - tensorboardX==2.6.2.2
    - triton==3.1.0